# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Redirección para el API de traducción
[[redirects]]
  from = "/api/translate"
  to = "/.netlify/functions/translate"
  status = 200
  force = true

[dev]
  port = 8888          # Puerto que Netlify Dev expone al navegador
  targetPort = 3000    # Puerto donde corre tu Vite dev server
  command = "npm run dev"
